=== BertrandD/mddl-server/dist/data/xsd/buildings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="building" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded" minOccurs="1">
								<xs:element name="modules" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="module" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="id" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="buildTime" minOccurs="1" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="fromLevel" type="xs:positiveInteger" use="required" />
													<xs:attribute name="toLevel" type="xs:positiveInteger" use="optional" />
													<xs:attribute name="function" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="stats" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="stat" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="name" use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="ENERGY" />
																<xs:enumeration value="BASE_MAX_HEALTH" />
																<xs:enumeration value="BASE_MAX_SHIELD" />
																<xs:enumeration value="BASE_MAX_STORAGE_VOLUME" />
																<xs:enumeration value="BUILD_COOLDOWN_REDUCTION" />
																<xs:enumeration value="RESOURCE_PRODUCTION_SPEED" />
																<xs:enumeration value="RESOURCE_FEO" />
																<xs:enumeration value="RESOURCE_C" />
																<xs:enumeration value="RESOURCE_CH4" />
																<xs:enumeration value="RESOURCE_ATO3" />
																<xs:enumeration value="RESOURCE_H2O" />
																<xs:enumeration value="MAX_RESOURCE_FEO" />
																<xs:enumeration value="MAX_RESOURCE_C" />
																<xs:enumeration value="MAX_RESOURCE_CH4" />
																<xs:enumeration value="MAX_RESOURCE_ATO3" />
																<xs:enumeration value="MAX_RESOURCE_H2O" />
															</xs:restriction>
														</xs:simpleType>
													</xs:attribute>
													<xs:attribute name="function" type="xs:string" use="required" />
													<xs:attribute name="op" use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="DIFF" />
																<xs:enumeration value="PER" />
															</xs:restriction>
														</xs:simpleType>
													</xs:attribute>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="energy" minOccurs="1" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="fromLevel" type="xs:positiveInteger" use="required" />
													<xs:attribute name="toLevel" type="xs:positiveInteger" use="optional" />
													<xs:attribute name="function" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="requirements" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="functions" minOccurs="0" maxOccurs="unbounded">
													<xs:complexType>
														<xs:sequence>
															<xs:choice minOccurs="1" maxOccurs="unbounded">
																<xs:element name="function" minOccurs="1" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="fromLevel" type="xs:positiveInteger" use="required" />
																		<xs:attribute name="toLevel" type="xs:positiveInteger" use="optional" />
																		<xs:attribute name="itemId" type="xs:string" use="required" />
																		<xs:attribute name="value" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:choice>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="requirement" minOccurs="0" maxOccurs="unbounded">
													<xs:complexType>
														<xs:sequence>
															<xs:choice maxOccurs="unbounded" minOccurs="1">
																<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:string" use="required" />
																		<xs:attribute name="count" type="xs:integer" use="required" />
																	</xs:complexType>
																</xs:element>
																<xs:element name="building" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:string" use="required" />
																		<xs:attribute name="level" type="xs:integer" use="required" />
																	</xs:complexType>
																</xs:element>
																<xs:element name="technology" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:string" use="required" />
																		<xs:attribute name="level" type="xs:integer" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:choice>
														</xs:sequence>
														<xs:attribute name="level" type="xs:integer" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="properties" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute name="name" type="xs:string" use="required" />
														<xs:attribute name="type" type="xs:string" use="optional" />
														<xs:attribute name="value" type="xs:string" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="propertiesByLevel" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute name="name" type="xs:string" use="required" />
														<xs:attribute name="value" type="xs:string" use="required" />
													</xs:complexType>
												</xs:element>
												<xs:element name="properties" minOccurs="0" maxOccurs="1">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="list" minOccurs="1" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
																			<xs:complexType>
																				<xs:attribute name="name" type="xs:string" use="required" />
																				<xs:attribute name="value" type="xs:string" use="required" />
																			</xs:complexType>
																		</xs:element>
																	</xs:sequence>
																	<xs:attribute name="name" type="xs:string" use="required" />
																</xs:complexType>
															</xs:element>
														</xs:sequence>
														<xs:attribute name="level" type="xs:integer" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
                        <xs:attribute name="id" type="xs:normalizedString" use="required" />
                        <xs:attribute name="nameId" type="xs:normalizedString" use="required" />
						<xs:attribute name="class" type="xs:string" use="required" />
                        <xs:attribute name="descriptionId" type="xs:normalizedString" use="required" />
                        <xs:attribute name="maxLevel" type="xs:positiveInteger" use="required"/>
						<xs:attribute name="maxBuild" type="xs:positiveInteger" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="disabled" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BertrandD/mddl-server/dist/data/stats/buildings/power_factory.xml
<?xml version="1.0" encoding="UTF-8"?>
<list disabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="power_factory" nameId="building_power_factory_n" type="PowerFactory" descriptionId="building_power_factory_d" maxLevel="1" buildTimeFunc="10*$level">
        <properties>
            <property name="production" value="(200 + (100 * $level))"/>
        </properties>
        <requirements>
            <requirement level="1">
                <item id="resource_steel" count="150" />
                <item id="resource_ch4" count="100" />
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/storage.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="storage" type="Storage" nameId="building_storage_n" maxLevel="5" descriptionId="building_storage_d">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,2.7)*1000*60" />
        </buildTime>
        <stats>
            <stat name="MAX_VOLUME" op="DIFF" />
        </stats>
        <properties>
            <property name="capacity" value="(1000+(Math.pow($level, 2)*100))*10" />
        </properties>
        <requirements>
            <functions>
                <function fromLevel="2" itemId="resource_c" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="2" itemId="resource_feo" value="0,2*Math.pow($level,4)"/>
            </functions>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/market.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="market" type="CommonBuilding" nameId="market_n" maxLevel="8" descriptionId="market_d">
        <buildTime>
            <set fromLevel="1" toLevel="5" function="5*$level" />
            <set fromLevel="6" function="10*$level" />
        </buildTime>
        <properties>
            <property name="cooldown_reduction" value="$cooldown - ($cooldown * ($level * 0.05))"/>
        </properties>
        <requirements>
            <functions>
                <function fromLevel="1" toLevel="4" itemId="resource_feo" value="100*(Math.pow($level,2))" />
                <function fromLevel="5" itemId="resource_steel" value="100*(Math.pow($level,2))" />
            </functions>
            <requirement level="3">
                <building id="mine_metal" level="1" />
            </requirement>
            <requirement level="5">
                <building id="mine" level="2" />
                <building id="storage" level="2" />
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/factory.xml
<?xml version="1.0" encoding="UTF-8"?>
<list disabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="factory" nameId="building_factory_n" type="Factory" descriptionId="building_factory_d" maxLevel="100">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,2.7)*1000*60" />
        </buildTime>
        <properties>
            <property name="availables_modules" value="module_building_factory_structure;module_building_factory_engine;module_building_factory_cargo;module_building_factory_weapon;module_building_factory_rafinery"/>
        </properties>
        <requirements>
            <requirement level="1">
                <item id="resource_feo" count="3000" />
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/operation_center.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="operation_center" nameId="building_operation_center_n" type="CommonBuilding" descriptionId="building_operation_center_d" maxLevel="10">
        <buildTime>
            <set fromLevel="1" function="5*$level" />
        </buildTime>
        <requirements>
            <requirement level="1">
                <item id="resource_feo" count="1500" />
                <item id="resource_c" count="150" />
                <item id="resource_h2o" count="200" />
                <item id="resource_ato3" count="25" />
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/embassy.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="embassy" nameId="building_embassy_n" type="CommonBuilding" descriptionId="building_embassy_d" maxLevel="5" buildTimeFunc="10*$level">
        <requirements>
            <requirement level="1">
                <item id="resource_feo" count="2000" />
                <item id="resource_h2o" count="300" />
                <item id="resource_ato3" count="50" />
            </requirement>
            <requirement level="2">
                <item id="resource_feo" count="3000" />
                <item id="resource_h2o" count="400" />
            </requirement>
            <requirement level="3">
                <item id="resource_feo" count="5000" />
                <item id="resource_h2o" count="600" />
            </requirement>
            <requirement level="4">
                <item id="resource_feo" count="10000" />
                <item id="resource_h2o" count="2500" />
            </requirement>
            <requirement level="5">
                <item id="resource_feo" count="20000" />
                <item id="resource_h2o" count="7500" />
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/middlewar-boot/src/main/resources/data/stats/buildings/embassy.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="embassy" nameId="building_embassy_n" class="CommonBuilding" descriptionId="building_embassy_d"
              maxLevel="5">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,1.4)*1000*10"/>
        </buildTime>
        <requirements>
            <requirement level="1">
                <item id="resource_1" count="2000"/>
                <item id="resource_5" count="300"/>
                <item id="resource_3" count="50"/>
            </requirement>
            <requirement level="2">
                <item id="resource_1" count="3000"/>
                <item id="resource_5" count="400"/>
            </requirement>
            <requirement level="3">
                <item id="resource_1" count="5000"/>
                <item id="resource_5" count="600"/>
            </requirement>
            <requirement level="4">
                <item id="resource_1" count="10000"/>
                <item id="resource_5" count="2500"/>
            </requirement>
            <requirement level="5">
                <item id="resource_1" count="20000"/>
                <item id="resource_5" count="7500"/>
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/robot_factory.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="robot_factory" type="RobotFactory" nameId="robot_factory_n" maxLevel="30" descriptionId="robot_factory_d">
        <buildTime>
            <set fromLevel="1" function="1750*$level" />
        </buildTime>
        <stats>
            <baseStat name="BUILD_COOLDOWN_REDUCTION" op="PER">
                <set function="($level * (0.0085))"/>
            </baseStat>
        </stats>
        <requirements>
            <functions>
                <function fromLevel="1" itemId="resource_ch4" value="100*$level"/>
            </functions>
        </requirements>
    </building>
</list>
