=== BertrandD/mddl-server/dist/data/xsd/buildings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="building" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded" minOccurs="1">
								<xs:element name="modules" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="module" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="id" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="buildTime" minOccurs="1" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="fromLevel" type="xs:positiveInteger" use="required" />
													<xs:attribute name="toLevel" type="xs:positiveInteger" use="optional" />
													<xs:attribute name="function" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="stats" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="stat" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="name" use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="ENERGY" />
																<xs:enumeration value="BASE_MAX_HEALTH" />
																<xs:enumeration value="BASE_MAX_SHIELD" />
																<xs:enumeration value="BASE_MAX_STORAGE_VOLUME" />
																<xs:enumeration value="BUILD_COOLDOWN_REDUCTION" />
																<xs:enumeration value="RESOURCE_PRODUCTION_SPEED" />
																<xs:enumeration value="RESOURCE_FEO" />
																<xs:enumeration value="RESOURCE_C" />
																<xs:enumeration value="RESOURCE_CH4" />
																<xs:enumeration value="RESOURCE_ATO3" />
																<xs:enumeration value="RESOURCE_H2O" />
																<xs:enumeration value="MAX_RESOURCE_FEO" />
																<xs:enumeration value="MAX_RESOURCE_C" />
																<xs:enumeration value="MAX_RESOURCE_CH4" />
																<xs:enumeration value="MAX_RESOURCE_ATO3" />
																<xs:enumeration value="MAX_RESOURCE_H2O" />
															</xs:restriction>
														</xs:simpleType>
													</xs:attribute>
													<xs:attribute name="function" type="xs:string" use="required" />
													<xs:attribute name="op" use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="DIFF" />
																<xs:enumeration value="PER" />
															</xs:restriction>
														</xs:simpleType>
													</xs:attribute>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="energy" minOccurs="1" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="fromLevel" type="xs:positiveInteger" use="required" />
													<xs:attribute name="toLevel" type="xs:positiveInteger" use="optional" />
													<xs:attribute name="function" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="requirements" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="functions" minOccurs="0" maxOccurs="unbounded">
													<xs:complexType>
														<xs:sequence>
															<xs:choice minOccurs="1" maxOccurs="unbounded">
																<xs:element name="function" minOccurs="1" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="fromLevel" type="xs:positiveInteger" use="required" />
																		<xs:attribute name="toLevel" type="xs:positiveInteger" use="optional" />
																		<xs:attribute name="itemId" type="xs:string" use="required" />
																		<xs:attribute name="value" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:choice>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="requirement" minOccurs="0" maxOccurs="unbounded">
													<xs:complexType>
														<xs:sequence>
															<xs:choice maxOccurs="unbounded" minOccurs="1">
																<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:string" use="required" />
																		<xs:attribute name="count" type="xs:integer" use="required" />
																	</xs:complexType>
																</xs:element>
																<xs:element name="building" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:string" use="required" />
																		<xs:attribute name="level" type="xs:integer" use="required" />
																	</xs:complexType>
																</xs:element>
																<xs:element name="technology" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:string" use="required" />
																		<xs:attribute name="level" type="xs:integer" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:choice>
														</xs:sequence>
														<xs:attribute name="level" type="xs:integer" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="properties" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute name="name" type="xs:string" use="required" />
														<xs:attribute name="type" type="xs:string" use="optional" />
														<xs:attribute name="value" type="xs:string" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="propertiesByLevel" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute name="name" type="xs:string" use="required" />
														<xs:attribute name="value" type="xs:string" use="required" />
													</xs:complexType>
												</xs:element>
												<xs:element name="properties" minOccurs="0" maxOccurs="1">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="list" minOccurs="1" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
																			<xs:complexType>
																				<xs:attribute name="name" type="xs:string" use="required" />
																				<xs:attribute name="value" type="xs:string" use="required" />
																			</xs:complexType>
																		</xs:element>
																	</xs:sequence>
																	<xs:attribute name="name" type="xs:string" use="required" />
																</xs:complexType>
															</xs:element>
														</xs:sequence>
														<xs:attribute name="level" type="xs:integer" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
                        <xs:attribute name="id" type="xs:normalizedString" use="required" />
                        <xs:attribute name="nameId" type="xs:normalizedString" use="required" />
						<xs:attribute name="class" type="xs:string" use="required" />
                        <xs:attribute name="descriptionId" type="xs:normalizedString" use="required" />
                        <xs:attribute name="maxLevel" type="xs:positiveInteger" use="required"/>
						<xs:attribute name="maxBuild" type="xs:positiveInteger" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="disabled" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BertrandD/mddl-server/api/src/test/resources/data/stats/buildings/extractors/pump.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/buildings.xsd">
    <building id="pump" nameId="building_pump_n" class="ModulableBuilding" descriptionId="building_pump_d" maxLevel="100">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,1.4)*1000*10" />
        </buildTime>
        <stats>
            <stat name="RESOURCE_4" function="100+(35*$level)" op="DIFF" />
            <stat name="RESOURCE_5" function="100+(100*$level)" op="DIFF" />
        </stats>
        <modules max="2">
            <module id="module_optimizer_5" />
            <module id="module_optimizer_4" />
        </modules>
        <requirements>
            <functions>
                <function fromLevel="2" itemId="resource_2" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="3" toLevel="8" itemId="resource_1" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="4" itemId="resource_3" value="0,2*Math.pow($level,4)"/>
            </functions>
            <requirement level="5">
                <building id="power_factory" level="2" />
                <item id="resource_5" count="250" />
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/resources/data/stats/buildings/silo.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="silo" class="ModulableBuilding" nameId="building_silo_n" maxLevel="5" maxBuild="5" descriptionId="building_silo_d">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,2.7)*1000*60" />
        </buildTime>
        <stats>
            <stat name="MAX_RESOURCE_FEO" function="(1000+(Math.pow($level, 2)*100))*10" op="DIFF" />
            <stat name="MAX_RESOURCE_C" function="(1000+(Math.pow($level, 2)*100))*10" op="DIFF" />
            <stat name="MAX_RESOURCE_CH4" function="(1000+(Math.pow($level, 2)*100))*10" op="DIFF" />
            <stat name="MAX_RESOURCE_ATO3" function="(1000+(Math.pow($level, 2)*100))*10" op="DIFF" />
            <stat name="MAX_RESOURCE_H2O" function="(1000+(Math.pow($level, 2)*100))*10" op="DIFF" />
        </stats>
        <modules max="1">
            <module id="module_silo_improve_feo" />
            <module id="module_silo_improve_c" />
            <module id="module_silo_improve_ato3" />
            <module id="module_silo_improve_ch4" />
            <module id="module_silo_improve_h2o" />
        </modules>
        <requirements>
            <functions>
                <function fromLevel="2" itemId="resource_c" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="2" itemId="resource_feo" value="0,2*Math.pow($level,4)"/>
            </functions>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/extractors/mine.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/buildings.xsd">
    <building id="mine" type="Extractor" nameId="building_mine_n" maxLevel="100" descriptionId="building_mine_d">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,2.7)*1000*60" />
        </buildTime>
        <energy>
            <set fromLevel="2" function="100 + ($level * 125)" />
        </energy>
        <modules>
            <module id="module_optimizer_feo" />
            <module id="module_optimizer_c" />
            <module id="module_optimizer_ato3" />
        </modules>
        <properties>
            <property name="max_modules" value="2" />
        </properties>
        <requirements>
            <functions>
                <function fromLevel="2" itemId="resource_feo" value="0,2*Math.pow($level,4)"/>
            </functions>
            <requirement level="1">
                <building id="storage" level="1" />
            </requirement>
        </requirements>
        <productions>
            <produce itemId="resource_feo" function="(18*Math.pow($level,2)+150)" />
            <produce itemId="resource_c" function="(18*Math.pow($level,2)+150)" />
            <produce itemId="resource_ato3" function="(18*Math.pow($level,2)+150)" />
        </productions>
    </building>
</list>

=== BertrandD/mddl-server/middlewar-api/src/test/resources/data/stats/buildings/extractors/mine.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/buildings.xsd">
    <building id="mine" class="ModulableBuilding" nameId="building_mine_n" maxLevel="100"
              descriptionId="building_mine_d">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,1.4)*1000*10"/>
        </buildTime>
        <energy>
            <set fromLevel="2" function="100 + ($level * 125)"/>
        </energy>
        <stats>
            <stat name="RESOURCE_1" function="1000" op="DIFF"/>
        </stats>
        <modules max="2">
            <module id="module_optimizer_1"/>
            <module id="module_optimizer_2"/>
            <module id="module_optimizer_3"/>
        </modules>
        <requirements>
            <functions>
                <function fromLevel="2" itemId="resource_1" value="0,2*Math.pow($level,4)"/>
            </functions>
            <requirement level="1">
                <building id="silo" level="1"/>
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/mine_metal.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="mine_metal" type="Mine" nameId="building_mine_metal_n" maxLevel="1" descriptionId="building_mine_metal_d" buildTimeFunc="5*$level">
        <requirements>
            <requirement level="1">
                <building id="headquarter" level="1" />
                <resource id="metal" count="300" />
            </requirement>
        </requirements>
        <properties>
            <property name="produce" value="metal" />
            <property name="produce_function" value="(100+(Math.pow($level, 2)))*10" />
        </properties>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/buildings.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="10000" type="HEADQUARTER" name="Headquarter" maxHealth="10000" maxLevel="50" buildTime="60" description="The Headquarter is the main building that allow you to manage your base.">
        <creation>
            <item id="100" count="1" />
            <item id="101" count="1" />
            <item id="102" count="1" />
        </creation>
    </building>
    <building id="10001" type="STORAGE" name="Storage" maxHealth="10000" maxLevel="50" buildTime="60" description="The Storage building is a important building to increase your storage capacity.">
        <creation>
            <item id="100" count="10" />
            <item id="101" count="10" />
            <item id="102" count="10" />
            <building type="HEADQUARTER" level="1" />
            <!--<technology id="" level="" />-->
        </creation>
    </building>
</list>

=== BertrandD/mddl-server/api/resources/data/stats/buildings/shield.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="shield" nameId="building_shield_n" class="ModulableBuilding" descriptionId="building_shield_d" maxLevel="10">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,1.4)*1000*10" />
        </buildTime>
        <stats>
            <stat name="BASE_MAX_SHIELD" function="1000 * $level" op="DIFF" />
        </stats>
        <modules max="1">
            <module id="module_building_shield_laser" />
            <module id="module_building_shield_ion" />
            <module id="module_building_shield_photon" />
            <module id="module_building_shield_plasma" />
            <module id="module_building_shield_graviton" />
        </modules>
        <requirements>
            <functions>
                <function fromLevel="1" itemId="resource_2" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="1" itemId="resource_3" value="0,2*Math.pow($level,4)"/>
            </functions>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/metal_storage.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="10001" type="STORAGE" name="Metal Storage" maxHealth="10000" maxLevel="20" buildTime="60" descriptionId="10001">
        <creations>
            <creation level="1">
                <item id="100" count="10" />
                <item id="101" count="10" />
                <item id="102" count="10" />
                <building id="10000" level="1" />
                <!--<technology id="" level="" />-->
            </creation>
            <creation level="2">
                <item id="100" count="10" />
                <item id="101" count="10" />
                <item id="102" count="10" />
                <building id="10000" level="1" />
            </creation>
            <creation level="3">
                <item id="100" count="10" />
                <item id="101" count="10" />
                <item id="102" count="10" />
                <building id="10000" level="1" />
            </creation>
        </creations>
        <properties>
            <maxStorage>
                <set level="1" value="1000" />
                <set level="2" value="3000" />
                <set level="3" value="8000" />
                <set level="4" value="15000" />
                <set level="5" value="25000" />
                <set level="6" value="50000" />
                <set level="7" value="85000" />
                <set level="8" value="125000" />
                <set level="9" value="250000" />
                <set level="10" value="500000" />
                <set level="11" value="900000" />
                <set level="12" value="145000" />
                <set level="13" value="2000000" />
                <set level="14" value="5000000" />
                <set level="15" value="12000000" />
                <set level="16" value="18000000" />
                <set level="17" value="25000000" />
                <set level="18" value="40000000" />
                <set level="19" value="80000000" />
                <set level="20" value="100000000" />
            </maxStorage>
        </properties>
    </building>
</list>
