=== BertrandD/mddl-server/dist/data/xsd/buildings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="building" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded" minOccurs="1">
								<xs:element name="modules" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="module" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="id" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="buildTime" minOccurs="1" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="fromLevel" type="xs:positiveInteger" use="required" />
													<xs:attribute name="toLevel" type="xs:positiveInteger" use="optional" />
													<xs:attribute name="function" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="stats" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="stat" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="name" use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="ENERGY" />
																<xs:enumeration value="BASE_MAX_HEALTH" />
																<xs:enumeration value="BASE_MAX_SHIELD" />
																<xs:enumeration value="BASE_MAX_STORAGE_VOLUME" />
																<xs:enumeration value="BUILD_COOLDOWN_REDUCTION" />
																<xs:enumeration value="RESOURCE_PRODUCTION_SPEED" />
																<xs:enumeration value="RESOURCE_FEO" />
																<xs:enumeration value="RESOURCE_C" />
																<xs:enumeration value="RESOURCE_CH4" />
																<xs:enumeration value="RESOURCE_ATO3" />
																<xs:enumeration value="RESOURCE_H2O" />
																<xs:enumeration value="MAX_RESOURCE_FEO" />
																<xs:enumeration value="MAX_RESOURCE_C" />
																<xs:enumeration value="MAX_RESOURCE_CH4" />
																<xs:enumeration value="MAX_RESOURCE_ATO3" />
																<xs:enumeration value="MAX_RESOURCE_H2O" />
															</xs:restriction>
														</xs:simpleType>
													</xs:attribute>
													<xs:attribute name="function" type="xs:string" use="required" />
													<xs:attribute name="op" use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="DIFF" />
																<xs:enumeration value="PER" />
															</xs:restriction>
														</xs:simpleType>
													</xs:attribute>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="energy" minOccurs="1" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="fromLevel" type="xs:positiveInteger" use="required" />
													<xs:attribute name="toLevel" type="xs:positiveInteger" use="optional" />
													<xs:attribute name="function" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="requirements" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="functions" minOccurs="0" maxOccurs="unbounded">
													<xs:complexType>
														<xs:sequence>
															<xs:choice minOccurs="1" maxOccurs="unbounded">
																<xs:element name="function" minOccurs="1" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="fromLevel" type="xs:positiveInteger" use="required" />
																		<xs:attribute name="toLevel" type="xs:positiveInteger" use="optional" />
																		<xs:attribute name="itemId" type="xs:string" use="required" />
																		<xs:attribute name="value" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:choice>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="requirement" minOccurs="0" maxOccurs="unbounded">
													<xs:complexType>
														<xs:sequence>
															<xs:choice maxOccurs="unbounded" minOccurs="1">
																<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:string" use="required" />
																		<xs:attribute name="count" type="xs:integer" use="required" />
																	</xs:complexType>
																</xs:element>
																<xs:element name="building" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:string" use="required" />
																		<xs:attribute name="level" type="xs:integer" use="required" />
																	</xs:complexType>
																</xs:element>
																<xs:element name="technology" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:string" use="required" />
																		<xs:attribute name="level" type="xs:integer" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:choice>
														</xs:sequence>
														<xs:attribute name="level" type="xs:integer" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="properties" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute name="name" type="xs:string" use="required" />
														<xs:attribute name="type" type="xs:string" use="optional" />
														<xs:attribute name="value" type="xs:string" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="propertiesByLevel" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute name="name" type="xs:string" use="required" />
														<xs:attribute name="value" type="xs:string" use="required" />
													</xs:complexType>
												</xs:element>
												<xs:element name="properties" minOccurs="0" maxOccurs="1">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="list" minOccurs="1" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
																			<xs:complexType>
																				<xs:attribute name="name" type="xs:string" use="required" />
																				<xs:attribute name="value" type="xs:string" use="required" />
																			</xs:complexType>
																		</xs:element>
																	</xs:sequence>
																	<xs:attribute name="name" type="xs:string" use="required" />
																</xs:complexType>
															</xs:element>
														</xs:sequence>
														<xs:attribute name="level" type="xs:integer" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
                        <xs:attribute name="id" type="xs:normalizedString" use="required" />
                        <xs:attribute name="nameId" type="xs:normalizedString" use="required" />
						<xs:attribute name="class" type="xs:string" use="required" />
                        <xs:attribute name="descriptionId" type="xs:normalizedString" use="required" />
                        <xs:attribute name="maxLevel" type="xs:positiveInteger" use="required"/>
						<xs:attribute name="maxBuild" type="xs:positiveInteger" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="disabled" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BertrandD/mddl-server/api/resources/data/stats/buildings/silo.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="silo" class="ModulableBuilding" nameId="building_silo_n" maxLevel="5" maxBuild="5" descriptionId="building_silo_d">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,1.4)*1000*10" />
        </buildTime>
        <stats>
            <stat name="MAX_RESOURCE_1" function="(1000+(Math.pow($level, 2)*100))*10" op="DIFF" />
            <stat name="MAX_RESOURCE_2" function="(1000+(Math.pow($level, 2)*100))*10" op="DIFF" />
            <stat name="MAX_RESOURCE_4" function="(1000+(Math.pow($level, 2)*100))*10" op="DIFF" />
            <stat name="MAX_RESOURCE_3" function="(1000+(Math.pow($level, 2)*100))*10" op="DIFF" />
            <stat name="MAX_RESOURCE_5" function="(1000+(Math.pow($level, 2)*100))*10" op="DIFF" />
        </stats>
        <modules max="1">
            <module id="module_silo_improve_1" />
            <module id="module_silo_improve_2" />
            <module id="module_silo_improve_3" />
            <module id="module_silo_improve_4" />
            <module id="module_silo_improve_5" />
        </modules>
        <requirements>
            <functions>
                <function fromLevel="2" itemId="resource_2" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="2" itemId="resource_1" value="0,2*Math.pow($level,4)"/>
            </functions>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/module_factory.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="module_factory" type="ModuleFactory" nameId="module_factory_n" maxLevel="8" descriptionId="module_factory_d" buildTimeFunc="10*$level">
        <propertiesByLevel>
            <properties level="1">
                <list name="unlock_modules">
                    <set name="module" value="module_optimizer_feo" />
                    <set name="module" value="module_optimizer_c" />
                </list>
            </properties>
            <properties level="2">
                <list name="unlock_modules">
                    <set name="module" value="module_optimizer_ato3" />
                </list>
            </properties>
        </propertiesByLevel>
        <requirements>
            <requirement level="1">
                <function type="ITEM" id="resource_feo" val="100*(Math.pow($level,2))" />
            </requirement>
            <requirement level="2">
                <function type="ITEM" id="resource_feo" val="100*(Math.pow($level,2))" />
            </requirement>
            <requirement level="3">
                <function type="ITEM" id="resource_steel" val="100*(Math.pow($level,2))" />
                <building id="mine_metal" level="1" />
            </requirement>
            <requirement level="4">
                <function type="ITEM" id="resource_steel" val="100*(Math.pow($level,2))" />
            </requirement>
            <requirement level="5">
                <function type="ITEM" id="resource_steel" val="100*(Math.pow($level,2))" />
                <building id="mine" level="2" />
                <building id="storage" level="2" />
            </requirement>
            <requirement level="6">
                <function type="ITEM" id="resource_steel" val="100*(Math.pow($level,2))" />
            </requirement>
            <requirement level="7">
                <function type="ITEM" id="resource_steel" val="100*(Math.pow($level,2))" />
            </requirement>
            <requirement level="8">
                <function type="ITEM" id="resource_steel" val="100*(Math.pow($level,2))" />
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/dist/data/stats/buildings/shield.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="shield" nameId="building_shield_n" type="Shield" descriptionId="building_shield_d" maxLevel="10">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,2.7)*1000*60" />
        </buildTime>
        <stats>
            <baseStat name="MAX_SHIELD" op="DIFF">
                <set function="1000 * $level"/>
            </baseStat>
        </stats>
        <modules>
            <module id="module_building_shield_laser" />
            <module id="module_building_shield_ion" />
            <module id="module_building_shield_photon" />
            <module id="module_building_shield_plasma" />
            <module id="module_building_shield_graviton" />
        </modules>
        <properties>
            <property name="max_modules" value="1" />
            <property name="armor" value="10000 + (5000 * $level)" />
        </properties>
        <requirements>
            <functions>
                <function fromLevel="1" itemId="resource_c" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="1" itemId="resource_ato3" value="0,2*Math.pow($level,4)"/>
            </functions>
        </requirements>
    </building>
</list>
