=== BertrandD/mddl-server/dist/data/xsd/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="common.xsd" />
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
                        <xs:sequence>
                            <xs:choice maxOccurs="unbounded" minOccurs="0">
                                <xs:element name="stats" type="element_stats" maxOccurs="1" />
                                <xs:element name="requirements" type="element_requirement" minOccurs="0" maxOccurs="1" />
                                <xs:element name="properties" minOccurs="0" maxOccurs="1">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="set" minOccurs="1" maxOccurs="unbounded">
                                                <xs:complexType>
                                                    <xs:attribute name="name" use="required">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="damage" />
                                                                <xs:enumeration value="unlock_stat" />
                                                                <xs:enumeration value="shield_defense" />
                                                                <xs:enumeration value="affected" />
                                                                <xs:enumeration value="multiplicator" />
                                                                <xs:enumeration value="power" />
                                                                <xs:enumeration value="capacity" />
                                                                <xs:enumeration value="slot_cargo" />
                                                                <xs:enumeration value="slot_engine" />
                                                                <xs:enumeration value="slot_module" />
                                                                <xs:enumeration value="slot_technology" />
                                                                <xs:enumeration value="slot_weapon" />
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:attribute>
                                                    <xs:attribute name="value" type="xs:string" use="required" />
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />
                        <xs:attribute name="nameId" type="xs:string" use="required" />
                        <xs:attribute name="type" type="xs:normalizedString" use="required" />
                        <xs:attribute name="descriptionId" type="xs:string" use="required" />
                        <xs:attribute name="rank" type="attribute_rank" use="optional" />
                        <xs:attribute name="buildTime" type="xs:long" use="optional" />
                        <xs:attribute name="weight" type="xs:long" use="optional" />
                        <xs:attribute name="volume" type="xs:long" use="optional" />
                        <xs:attribute name="rarity" type="xs:integer" use="optional" />
                    </xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BertrandD/mddl-server/dist/data/stats/items/modules/module_extractor.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/items.xsd">
    <!-- Resources Optimizers -->
    <item id="module_optimizer_feo" nameId="module_optimizer_feo_n" type="MODULE" descriptionId="module_optimizer_feo_d" volume="1">
        <stats>
            <set stat="RESOURCE_FEO" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_feo" count="100" />
            <item id="resource_h2o" count="100" />
            <item id="resource_c" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_c" nameId="module_optimizer_c_n" type="MODULE" descriptionId="module_optimizer_c_d" volume="1">
        <stats>
            <set stat="RESOURCE_C" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_feo" count="100" />
            <item id="resource_h2o" count="100" />
            <item id="resource_c" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_ato3" nameId="module_optimizer_ato3_n" type="MODULE" descriptionId="module_optimizer_ato3_d" volume="1">
        <stats>
            <set stat="RESOURCE_ATO3" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_feo" count="100" />
            <item id="resource_h2o" count="100" />
            <item id="resource_c" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_ch4" nameId="module_optimizer_ch4_n" type="MODULE" descriptionId="module_optimizer_ch4_d" volume="1">
        <stats>
            <set stat="RESOURCE_CH4" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_feo" count="100" />
            <item id="resource_h2o" count="100" />
            <item id="resource_c" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_h2o" nameId="module_optimizer_h2o_n" type="MODULE" descriptionId="module_optimizer_h2o_d" volume="1">
        <stats>
            <set stat="RESOURCE_H2O" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_feo" count="100" />
            <item id="resource_h2o" count="100" />
            <item id="resource_c" count="100" />
        </requirements>
    </item>
</list>

=== BertrandD/mddl-server/api/resources/data/stats/items/modules/module_extractor.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/items.xsd">
    <!-- Resources Optimizers -->
    <item id="module_optimizer_1" nameId="module_optimizer_1_n" type="MODULE" descriptionId="module_optimizer_1_d" volume="0">
        <stats>
            <stat name="RESOURCE_1" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_1" count="100" />
            <item id="resource_5" count="100" />
            <item id="resource_2" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_2" nameId="module_optimizer_2_n" type="MODULE" descriptionId="module_optimizer_2_d" volume="0">
        <stats>
            <stat name="RESOURCE_2" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_1" count="100" />
            <item id="resource_5" count="100" />
            <item id="resource_2" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_3" nameId="module_optimizer_3_n" type="MODULE" descriptionId="module_optimizer_3_d" volume="0">
        <stats>
            <stat name="RESOURCE_3" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_1" count="100" />
            <item id="resource_5" count="100" />
            <item id="resource_2" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_4" nameId="module_optimizer_4_n" type="MODULE" descriptionId="module_optimizer_4_d" volume="0">
        <stats>
            <stat name="RESOURCE_4" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_1" count="100" />
            <item id="resource_5" count="100" />
            <item id="resource_2" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_5" nameId="module_optimizer_5_n" type="MODULE" descriptionId="module_optimizer_5_d" volume="0">
        <stats>
            <stat name="RESOURCE_5" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_1" count="100" />
            <item id="resource_5" count="100" />
            <item id="resource_2" count="100" />
        </requirements>
    </item>
</list>

=== BertrandD/mddl-server/dist/data/stats/items/structures.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
    <item id="10000" type="STRUCTURE" nameId="asti1" rank="A" buildTime="60" descriptionId="asti1_d">
        <requirement>
            <item id="metal" count="50" />
        </requirement>
        <properties>
            <set name="slot_cargo" value="0" />
            <set name="slot_engine" value="1" />
            <set name="slot_module" value="1" />
            <set name="slot_technology" value="1" />
            <set name="slot_weapon" value="0" />
        </properties>
    </item>
    <item id="10001" type="STRUCTURE" nameId="asti2" rank="B" buildTime="60" descriptionId="asti2_d">
        <requirement>
            <item id="metal" count="100" />
        </requirement>
        <properties>
            <set name="slot_cargo" value="1" />
            <set name="slot_engine" value="1" />
            <set name="slot_module" value="2" />
            <set name="slot_technology" value="2" />
            <set name="slot_weapon" value="1" />
        </properties>
    </item>
    <item id="10002" type="STRUCTURE" nameId="asti3" rank="C" buildTime="60" descriptionId="asti3_d">
        <requirement>
            <item id="metal" count="275" />
        </requirement>
        <properties>
            <set name="slot_cargo" value="2" />
            <set name="slot_engine" value="2" />
            <set name="slot_module" value="2" />
            <set name="slot_technology" value="2" />
            <set name="slot_weapon" value="2" />
        </properties>
    </item>
    <item id="10003" type="STRUCTURE" nameId="asti4" rank="D" buildTime="60" descriptionId="asti4_d">
        <requirement>
            <item id="metal" count="600" />
        </requirement>
        <properties>
            <set name="slot_cargo" value="4" />
            <set name="slot_engine" value="4" />
            <set name="slot_module" value="3" />
            <set name="slot_technology" value="2" />
            <set name="slot_weapon" value="4" />
        </properties>
    </item>
    <item id="10004" type="STRUCTURE" nameId="asti5" rank="E" buildTime="60" descriptionId="asti5_d">
        <requirement>
            <item id="metal" count="1000" />
        </requirement>
        <properties>
            <set name="slot_cargo" value="10" />
            <set name="slot_engine" value="6" />
            <set name="slot_module" value="4" />
            <set name="slot_technology" value="4" />
            <set name="slot_weapon" value="8" />
        </properties>
    </item>
</list>

=== BertrandD/mddl-server/dist/data/stats/items/modules/module_silo.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/items.xsd">
    <!-- Silo specialization -->
    <item id="module_silo_improve_feo" nameId="module_silo_improve_feo_n" type="MODULE" descriptionId="module_silo_improve_feo_d" >
        <properties>
            <set name="unlock_stat" value="MAX_RESOURCE_FEO"/>
        </properties>
    </item>
    <item id="module_silo_improve_c" nameId="module_silo_improve_c_n" type="MODULE" descriptionId="module_silo_improve_c_d" >
        <properties>
            <set name="unlock_stat" value="MAX_RESOURCE_C"/>
        </properties>
    </item>
    <item id="module_silo_improve_ato3" nameId="module_silo_improve_ato3_n" type="MODULE" descriptionId="module_silo_improve_ato3_d" >
        <properties>
            <set name="unlock_stat" value="MAX_RESOURCE_ATO3"/>
        </properties>
    </item>
    <item id="module_silo_improve_ch4" nameId="module_silo_improve_ch4_n" type="MODULE" descriptionId="module_silo_improve_ch4_d" >
        <properties>
            <set name="unlock_stat" value="MAX_RESOURCE_CH4"/>
        </properties>
    </item>
    <item id="module_silo_improve_h2o" nameId="module_silo_improve_h2o_n" type="MODULE" descriptionId="module_silo_improve_h2o_d" >
        <properties>
            <set name="unlock_stat" value="MAX_RESOURCE_H2O"/>
        </properties>
    </item>
</list>

=== BertrandD/mddl-server/middlewar-boot/src/main/resources/data/stats/items/resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
    <item id="resource_1" type="RESOURCE" nameId="resource_1_n" descriptionId="resource_1_d" volume="1" rarity="1"/>
    <item id="resource_2" type="RESOURCE" nameId="resource_2_n" descriptionId="resource_2_d" volume="1" rarity="1"/>
    <item id="resource_3" type="RESOURCE" nameId="resource_3_n" descriptionId="resource_3_d" volume="1" rarity="3"/>
    <item id="resource_4" type="RESOURCE" nameId="resource_4_n" descriptionId="resource_4_d" volume="1" rarity="2"/>
    <item id="resource_5" type="RESOURCE" nameId="resource_5_n" descriptionId="resource_5_d" volume="1" rarity="2"/>
    <item id="resource_steel" type="COMMON" nameId="resource_steel_n" descriptionId="resource_steel_d" volume="1">
        <requirements>
            <item id="resource_1" count="100"/>
            <item id="resource_2" count="100"/>
        </requirements>
    </item>
    <item id="resource_plastic" type="COMMON" nameId="resource_plastic_n" descriptionId="resource_plastic_d" volume="1">
        <requirements>
            <item id="resource_4" count="100"/>
        </requirements>
    </item>
    <item id="resource_tool" type="COMMON" nameId="resource_tool_n" descriptionId="resource_tool_d" volume="1">
        <requirements>
            <item id="resource_steel" count="100"/>
            <item id="resource_plastic" count="100"/>
        </requirements>
    </item>
    <item id="resource_nanoliquid" type="COMMON" nameId="resource_nanoliquid_n" descriptionId="resource_nanoliquid_d"
          volume="1">
        <requirements>
            <item id="resource_3" count="75"/>
            <item id="resource_4" count="30"/>
            <item id="resource_5" count="60"/>
        </requirements>
    </item>
    <item id="resource_septum" type="COMMON" nameId="resource_septum_n" descriptionId="resource_septum_d" volume="1">
        <requirements>
            <item id="resource_nanoliquid" count="100"/>
        </requirements>
    </item>
</list>

=== BertrandD/mddl-server/dist/data/stats/items/cargos.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
    <item id="11000" type="CARGO" name="ACTI I" rank="A" weight="200" sellable="true" tradable="true" disabled="false" buildTime="300" descriptionId="-1">
        <creation>
            <item id="100" count="5000" />
            <item id="101" count="1000" />
            <item id="102" count="1000" />
        </creation>
        <properties>
            <set name="capacity" value="10" />
        </properties>
    </item>
    <item id="11001" type="CARGO" name="ACTI II" rank="A" weight="230" sellable="true" tradable="true" disabled="false" buildTime="300" descriptionId="-1">
        <creation>
            <item id="100" count="5000" />
            <item id="101" count="1000" />
            <item id="102" count="1000" />
        </creation>
        <properties>
            <set name="capacity" value="13" />
        </properties>
    </item>
</list>

=== BertrandD/mddl-server/dist/data/stats/items/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
    <!-- Resources Optimizers -->
    <item id="module_optimizer_feo" nameId="module_optimizer_feo_n" type="MODULE" descriptionId="module_optimizer_feo_d" volume="1">
        <stats>
            <set stat="RESOURCE_FEO" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_feo" count="100" />
            <item id="resource_h2o" count="100" />
            <item id="resource_c" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_c" nameId="module_optimizer_c_n" type="MODULE" descriptionId="module_optimizer_c_d" volume="1">
        <stats>
            <set stat="RESOURCE_C" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_feo" count="100" />
            <item id="resource_h2o" count="100" />
            <item id="resource_c" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_ato3" nameId="module_optimizer_ato3_n" type="MODULE" descriptionId="module_optimizer_ato3_d" volume="1">
        <stats>
            <set stat="RESOURCE_ATO3" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_feo" count="100" />
            <item id="resource_h2o" count="100" />
            <item id="resource_c" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_ch4" nameId="module_optimizer_ch4_n" type="MODULE" descriptionId="module_optimizer_ch4_d" volume="1">
        <stats>
            <set stat="RESOURCE_CH4" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_feo" count="100" />
            <item id="resource_h2o" count="100" />
            <item id="resource_c" count="100" />
        </requirements>
    </item>
    <item id="module_optimizer_h2o" nameId="module_optimizer_h2o_n" type="MODULE" descriptionId="module_optimizer_h2o_d" volume="1">
        <stats>
            <set stat="RESOURCE_H2O" op="PER" value="1.25" />
        </stats>
        <requirements>
            <item id="resource_feo" count="100" />
            <item id="resource_h2o" count="100" />
            <item id="resource_c" count="100" />
        </requirements>
    </item>
    <!-- Silo specialization -->
    <item id="module_silo_improve_feo" nameId="module_silo_improve_feo_n" type="MODULE" descriptionId="module_silo_improve_feo_d" >
        <properties>
            <set name="unlock_stat" value="MAX_RESOURCE_FEO"/>
        </properties>
    </item>
    <item id="module_silo_improve_c" nameId="module_silo_improve_c_n" type="MODULE" descriptionId="module_silo_improve_c_d" >
        <properties>
            <set name="unlock_stat" value="MAX_RESOURCE_C"/>
        </properties>
    </item>
    <item id="module_silo_improve_ato3" nameId="module_silo_improve_ato3_n" type="MODULE" descriptionId="module_silo_improve_ato3_d" >
        <properties>
            <set name="unlock_stat" value="MAX_RESOURCE_ATO3"/>
        </properties>
    </item>
    <item id="module_silo_improve_ch4" nameId="module_silo_improve_ch4_n" type="MODULE" descriptionId="module_silo_improve_ch4_d" >
        <properties>
            <set name="unlock_stat" value="MAX_RESOURCE_CH4"/>
        </properties>
    </item>
    <item id="module_silo_improve_h2o" nameId="module_silo_improve_h2o_n" type="MODULE" descriptionId="module_silo_improve_h2o_d" >
        <properties>
            <set name="unlock_stat" value="MAX_RESOURCE_H2O"/>
        </properties>
    </item>
    <!-- Building Specializations -->
    <item id="module_building_factory_structure" nameId="module_building_factory_structure_n" type="MODULE" descriptionId="module_building_factory_structure_d" />
    <item id="module_building_factory_engine" nameId="module_building_factory_engine_n" type="MODULE" descriptionId="module_building_factory_engine_d" />
    <item id="module_building_factory_cargo" nameId="module_building_factory_cargo_n" type="MODULE" descriptionId="module_building_factory_cargo_d" />
    <item id="module_building_factory_weapon" nameId="module_building_factory_weapon_n" type="MODULE" descriptionId="module_building_factory_weapon_d" />
    <item id="module_building_factory_rafinery" nameId="module_building_factory_rafinery_n" type="MODULE" descriptionId="module_building_factory_rafinery_d" />
    <item id="module_building_shield_laser" nameId="module_building_shield_laser_n" type="MODULE" descriptionId="module_building_shield_laser_d">
        <properties>
            <set name="shield_defense" value="technology_laser"/>
        </properties>
    </item>
    <item id="module_building_shield_ion" nameId="module_building_shield_ion_n" type="MODULE" descriptionId="module_building_shield_ion_d">
        <properties>
            <set name="shield_defense" value="technology_ion"/>
        </properties>
    </item>
    <item id="module_building_shield_photon" nameId="module_building_shield_photon_n" type="MODULE" descriptionId="module_building_shield_photon_d">
        <properties>
            <set name="shield_defense" value="technology_photon"/>
        </properties>
    </item>
    <item id="module_building_shield_plasma" nameId="module_building_shield_plasma_n" type="MODULE" descriptionId="module_building_shield_plasma_d">
        <properties>
            <set name="shield_defense" value="technology_plasma"/>
        </properties>
    </item>
    <item id="module_building_shield_graviton" nameId="module_building_shield_graviton_n" type="MODULE" descriptionId="module_building_shield_graviton_d">
        <properties>
            <set name="shield_defense" value="technology_graviton"/>
        </properties>
    </item>
</list>

=== BertrandD/mddl-server/middlewar-api/src/test/resources/data/stats/items/structures.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
    <item id="structure_test" type="STRUCTURE" nameId="structure_test_n" descriptionId="structure_test_d" rank="A"
          buildTime="60" volume="72">
        <properties>
            <set name="slot_weapon" value="1"/>
        </properties>
        <requirements>
            <item id="resource_1" count="1"/>
        </requirements>
    </item>
    <item id="structure_test_many_slots" type="STRUCTURE" nameId="structure_test_n" descriptionId="structure_test_d" rank="A"
          buildTime="60" volume="72">
        <properties>
            <set name="slot_weapon" value="2"/>
            <set name="slot_cargo" value="2"/>
            <set name="slot_engine" value="2"/>
            <set name="slot_module" value="2"/>
            <set name="slot_technology" value="2"/>
        </properties>
        <requirements>
            <item id="resource_1" count="1"/>
        </requirements>
    </item>
</list>
