=== BertrandD/mddl-server/api/resources/data/xsd/buildings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="common.xsd" />
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="building" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded" minOccurs="1">
								<xs:element name="modules" type="element_modules" minOccurs="0" maxOccurs="1" />
								<xs:element name="buildTime" type="element_buildTime" minOccurs="1" maxOccurs="1" />
								<xs:element name="stats" type="element_stats" minOccurs="0" maxOccurs="1" />
								<xs:element name="energy" type="element_energy" minOccurs="0" maxOccurs="1" />
								<xs:element name="requirements" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="functions" minOccurs="0" maxOccurs="unbounded">
													<xs:complexType>
														<xs:sequence>
															<xs:choice minOccurs="1" maxOccurs="unbounded">
																<xs:element name="function" type="element_function" minOccurs="1" maxOccurs="unbounded" />
															</xs:choice>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="requirement" type="element_requirement" minOccurs="0" maxOccurs="unbounded" />
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="properties" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute name="name" type="xs:string" use="required" />
														<xs:attribute name="type" type="xs:string" use="optional" />
														<xs:attribute name="value" type="xs:string" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="propertiesByLevel" minOccurs="0" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:choice maxOccurs="unbounded" minOccurs="1">
												<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute name="name" type="xs:string" use="required" />
														<xs:attribute name="value" type="xs:string" use="required" />
													</xs:complexType>
												</xs:element>
												<xs:element name="properties" minOccurs="0" maxOccurs="1">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="list" minOccurs="1" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
																			<xs:complexType>
																				<xs:attribute name="name" type="xs:string" use="required" />
																				<xs:attribute name="value" type="xs:string" use="required" />
																			</xs:complexType>
																		</xs:element>
																	</xs:sequence>
																	<xs:attribute name="name" type="xs:string" use="required" />
																</xs:complexType>
															</xs:element>
														</xs:sequence>
														<xs:attribute name="level" type="xs:integer" use="required" />
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
                        <xs:attribute name="id" type="xs:normalizedString" use="required" />
                        <xs:attribute name="nameId" type="xs:normalizedString" use="required" />
						<xs:attribute name="class" type="xs:string" use="required" />
                        <xs:attribute name="descriptionId" type="xs:normalizedString" use="required" />
                        <xs:attribute name="maxLevel" type="xs:positiveInteger" use="required"/>
						<xs:attribute name="maxBuild" type="xs:positiveInteger" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="disabled" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BertrandD/mddl-server/api/resources/data/stats/buildings/operation_center.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="operation_center" nameId="building_operation_center_n" class="CommonBuilding" descriptionId="building_operation_center_d" maxLevel="10">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,1.4)*1000*10" />
        </buildTime>
        <requirements>
            <functions>
                <function fromLevel="1" itemId="resource_1" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="1" itemId="resource_2" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="1" itemId="resource_5" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="1" itemId="resource_3" value="0,2*Math.pow($level,4)"/>
            </functions>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/resources/data/stats/buildings/spatial_elevator.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="spatial_elevator" class="CommonBuilding" nameId="building_spatial_elevator_n" maxLevel="5" descriptionId="building_spatial_elevator_d">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,2.7)*1000*60" />
        </buildTime>
        <requirements>
            <functions>
                <function fromLevel="1" toLevel="5" itemId="resource_feo" value="0,2*Math.pow($level,4)" />
            </functions>
            <requirement level="3">
                <building id="operation_center" level="2" />
            </requirement>
            <requirement level="5">
                <building id="shield" level="2" />
                <building id="operation_center" level="5" />
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/api/resources/data/stats/buildings/robot_factory.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="robot_factory" class="CommonBuilding" nameId="building_robot_factory_n" maxLevel="30" descriptionId="building_robot_factory_d">
        <buildTime>
            <set fromLevel="1" function="1750*$level" />
        </buildTime>
        <stats>
            <stat name="BUILD_COOLDOWN_REDUCTION" function="($level * (0.0085))" op="PER" />
        </stats>
        <requirements>
            <functions>
                <function fromLevel="1" itemId="resource_ch4" value="100*$level"/>
            </functions>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/middlewar-api/src/test/resources/data/stats/buildings/silo_req_building.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="silo_req_building" type="test" class="ModulableBuilding" nameId="building_silo_n" maxLevel="5" maxBuild="5" descriptionId="building_silo_d">
        <buildTime>
            <set fromLevel="1" function="0" />
        </buildTime>
        <stats>
            <stat name="MAX_RESOURCE_1" function="1000" op="DIFF" />
        </stats>
        <modules max="1">
            <module id="module_silo_improve_1" />
        </modules>
        <requirements>
            <requirement level="1">
                <building id="silo" level="2"/>
            </requirement>
            <functions>
                <function fromLevel="1" itemId="resource_1" value="100"/>
            </functions>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/middlewar-boot/src/main/resources/data/stats/buildings/market.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="market" class="CommonBuilding" nameId="building_market_n" maxLevel="100"
              descriptionId="building_market_d">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,1.4)*1000*10"/>
        </buildTime>
        <requirements>
            <functions>
                <function fromLevel="1" toLevel="4" itemId="resource_1" value="0,2*Math.pow($level,4)"/>
                <function fromLevel="5" itemId="resource_steel" value="0,2*Math.pow($level,4)"/>
            </functions>
            <requirement level="3">
                <building id="mine" level="1"/>
                <item id="dfd" count="5"/>
            </requirement>
            <requirement level="5">
                <building id="mine" level="2"/>
                <building id="storage" level="2"/>
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/middlewar-boot/src/main/resources/data/stats/buildings/structure_factory.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="structure_factory" class="StructureFactory" nameId="building_structure_factory_n" maxLevel="25" descriptionId="building_structure_factory_d">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,1.4)*1000*10" />
        </buildTime>
        <propertiesByLevel>
            <properties level="1">
                <list name="unlock_structures">
                    <set name="structure" value="structure_test" />
                </list>
            </properties>
        </propertiesByLevel>
        <requirements>
            <functions>
                <function fromLevel="2" itemId="resource_1" value="0,2*Math.pow($level,4)"/>
            </functions>
            <requirement level="5">
                <building id="mine" level="2" />
                <building id="storage" level="2" />
            </requirement>
        </requirements>
    </building>
</list>

=== BertrandD/mddl-server/middlewar-api/src/test/resources/data/stats/buildings/module_factory.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buildings.xsd">
    <building id="module_factory" class="ModuleFactory" nameId="building_module_factory_n" maxLevel="25"
              descriptionId="building_module_factory_d">
        <buildTime>
            <set fromLevel="1" function="Math.pow($level,1.4)*1000*10"/>
        </buildTime>
        <propertiesByLevel>
            <properties level="1">
                <list name="unlock_modules">
                    <set name="module" value="module_silo_improve_1"/>
                    <set name="module" value="module_silo_improve_2"/>
                </list>
            </properties>
            <properties level="2">
                <list name="unlock_modules">
                    <set name="module" value="module_silo_improve_3"/>
                    <set name="module" value="module_silo_improve_4"/>
                    <set name="module" value="module_silo_improve_5"/>
                    <set name="module" value="module_optimizer_1"/>
                </list>
            </properties>
            <properties level="3">
                <list name="unlock_modules">
                    <set name="module" value="module_optimizer_2"/>
                </list>
            </properties>
            <properties level="5">
                <list name="unlock_modules">
                    <set name="module" value="module_optimizer_4"/>
                    <set name="module" value="module_optimizer_3"/>
                </list>
            </properties>
            <properties level="7">
                <list name="unlock_modules">
                    <set name="module" value="module_optimizer_5"/>
                </list>
            </properties>
        </propertiesByLevel>
        <requirements>
            <functions>
                <function fromLevel="2" itemId="resource_1" value="0,2*Math.pow($level,4)"/>
            </functions>
            <requirement level="5">
                <building id="mine" level="2"/>
                <building id="storage" level="2"/>
            </requirement>
        </requirements>
    </building>
</list>
