=== BertrandD/mddl-server/api/resources/data/xsd/messages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="messages" type="messageListType" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="messageType">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="text" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="messageListType">
        <xs:sequence>
            <xs:element name="message" type="messageType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="lang" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="EN" />
                    <xs:enumeration value="FR" />
                    <xs:enumeration value="CH" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== BertrandD/mddl-server/dist/data/messages/en.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/messages.xsd">
    <messages lang="EN">
        <!-- Account -->
        <message id="username_not_found" text="Username not found" />
        <message id="username_already_exist" text="Username already exist" />
        <message id="account_already_exist" text="Account already exist" />
        <message id="incorrect_credentials" text="Incorrect credentials" />
        <!-- Commons -->
        <message id="forbidden_name" text="Forbidden name" />
        <!-- Player -->
        <message id="player_not_found" text="Player not found" />
        <!-- Base -->
        <message id="base_not_found" text="Base not found" />
    </messages>
</list>

=== BertrandD/mddl-server/middlewar-boot/src/main/resources/data/messages/fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/messages.xsd">
    <messages lang="FR">
        <!-- Account -->
        <message id="username_not_found" text="Nom d'utilisateur inconnu"/>
        <message id="username_already_exist" text="Nom d'utilisateur déjà utilisé"/>
        <message id="account_already_exist" text="Ce compte existe déjà"/>
        <message id="incorrect_credentials" text="Mot de passe incorrect"/>
        <!-- FriendRequest -->
        <message id="friendrequest_doesnt_exist" text="La requête n'existe pas"/>
        <message id="friendrequest_faile_to_send_friend_request" text="La requête d'ami n'a pas abouti"/>
        <message id="friendrequest_you_cannot_request_yourself"
                 text="Vous ne pouvez pas vous demandez vous-même en ami"/>
        <!-- Commons -->
        <message id="forbidden_name" text="Ce nom est interdit"/>
        <!-- Player -->
        <message id="player_not_found" text="Ce joueur n'existe pas"/>
        <message id="choose_player" text="Sélectionnez un personnage"/>
        <message id="maximum_player_creation_reached" text="Limite de création de personnages atteinte"/>
        <message id="player_creation_failed" text="La création du joueur à échoué"/>
        <!-- Base -->
        <message id="base_not_found" text="Cette base n'existe pas"/>
        <message id="base_position_already_taken" text="Cette position est déjà prise"/>
        <!-- Static buildings -->
        <message id="static_building_doesnt_exist" text="Le batiment demandé n'existe pas !"/>
        <!-- Buildings -->
        <message id="building_cannot_create" text="Erreur lors de la creation du batiment"/>
        <message id="building_not_found" text="Le batiment n'existe pas"/>
        <message id="building_already_exist" text="Le batiment existe déjà"/>
        <message id="building_max_level_reached" text="Niveau maximum atteint pour ce batiment."/>
        <!-- Buildings names -->
        <message id="building_mine_n" text="Mine"/>
        <message id="building_storage_n" text="Hangar"/>
        <message id="building_shield_n" text="Bouclier"/>
        <message id="building_pump_n" text="Pompe"/>
        <message id="building_power_factory_n" text="Centrale énergétique"/>
        <message id="building_embassy_n" text="Ambassade"/>
        <message id="building_operation_center_n" text="Centre opérationnel"/>
        <message id="building_robot_factory_n" text="Usine de robots"/>
        <message id="building_market_n" text="Marché"/>
        <message id="building_module_factory_n" text="Usine de modules"/>
        <message id="building_structure_factory_n" text="Usine de structures"/>
        <message id="building_spatial_elevator_n" text="Station de lancement"/>
        <message id="building_silo_n" text="Silo"/>
        <!-- Buildings descriptions -->
        <message id="building_mine_d"
                 text="La mine permet l'extraction de ressources précieuses contenue dans les entrailles de la planète."/>
        <message id="building_storage_d"
                 text="Le hangar augmente la capacité de stockage de votre base. Augmentez son niveau pour obtenir le niveau de stockage désiré."/>
        <message id="building_shield_d"
                 text="Le bouclier est un batiment defensif vous protégeant des attaques et raids venant d'éventuels ennemis."/>
        <message id="building_pump_d" text="La pompe est un batiment essentiel pour extraire les ressources liquides."/>
        <message id="building_power_factory_d"
                 text="La centrale énergétique génère l'energie consommées par les batiments pour exploité la maximum de leur capacités."/>
        <message id="building_embassy_d" text="L'ambassade est destinée à la gestion des relations extérieurs."/>
        <message id="building_operation_center_d"
                 text="Le centre opérationnel permet la gestion des flottes entrantes et sortante de la base"/>
        <message id="building_robot_factory_d" text="Fr: description is not done, its in todo list"/>
        <message id="building_market_d" text="Fr: description is not done, its in todo list"/>
        <message id="building_module_factory_d" text="Fr: description is not done, its in todo list"/>
        <message id="building_structure_factory_d" text="Fr: description is not done, its in todo list"/>
        <message id="building_structure_factory_d" text="Fr: description is not done, its in todo list"/>
        <message id="building_spatial_elevator_d" text="Description is not done, its in todo list"/>
        <message id="building_silo_d" text="Fr: description is not done, its in todo list"/>
        <!-- Items -->
        <message id="item_not_found" text="Item not found"/>
        <message id="item_not_found_in_inventory" text="Item not found in inventory"/>
        <message id="item_cannot_create" text="Item cannot be created"/>
        <!-- Inventories -->
        <message id="inventory_not_found" text="Inventory not found"/>
        <!-- Requirements -->
        <message id="you_dont_meet_building_requirement" text="Vous n'avez pas tous les bâtiments nécessaires"/>
        <message id="you_dont_meet_item_requirement" text="Vous n'avez pas tous les objets nécessaires"/>
        <message id="you_dont_meet_resource_requirement" text="Vous n'avez pas toutes les ressources nécessaires"/>
        <!-- Items names -->
        <message id="resource_1_n" text="Métal"/>
        <message id="resource_2_n" text="Carbone"/>
        <message id="resource_3_n" text="Cristal"/>
        <message id="resource_4_n" text="Méthane"/>
        <message id="resource_5_n" text="Eau"/>
        <message id="resource_steel_n" text="Acier"/>
        <message id="resource_plastic_n" text="Plastique"/>
        <message id="resource_tool_n" text="Outil"/>
        <message id="resource_nanoliquid_n" text="Nanoliquide"/>
        <message id="resource_septum_n" text="Septum"/>
        <message id="structure_test_n" text="Structure Test"/>
        <!-- Items descriptions -->
        <message id="resource_1_d" text="Oxyde de Fer"/>
        <message id="resource_2_d" text="Carbone"/>
        <message id="resource_3_d" text="Oxyde d'atemium"/>
        <message id="resource_4_d" text="Méthane"/>
        <message id="resource_5_d" text="Eau"/>
        <message id="resource_steel_d"
                 text="L'acier est une resource primaire destinée à la création de batiment et des composants nécessaires aux vaisseaux"/>
        <message id="resource_plastic_d" text="Plastique"/>
        <message id="resource_tool_d" text="Outil"/>
        <message id="resource_nanoliquid_d" text="Nanoliquide"/>
        <message id="resource_septum_d" text="Septum"/>
        <message id="structure_test_d" text="Structure créée pour effectuer des tests. A supprimer avant la release."/>
    </messages>
</list>

=== BertrandD/mddl-server/api/resources/data/messages/en.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/messages.xsd">
    <messages lang="EN">
        <!-- Account -->
        <message id="username_not_found" text="Username not found" />
        <message id="username_already_exist" text="Username already exist" />
        <message id="account_already_exist" text="Account already exist" />
        <message id="incorrect_credentials" text="Incorrect credentials" />
        <!-- FriendRequest -->
        <message id="friendrequest_doesnt_exist" text="The request doesn't exist" />
        <message id="friendrequest_faile_to_send_friend_request" text="Failed to send friend request" />
        <message id="friendrequest_you_cannot_request_yourself" text="You cannot request yourself" />
        <!-- Commons -->
        <message id="forbidden_name" text="Forbidden name" />
        <!-- Player -->
        <message id="player_not_found" text="Player not found" />
        <message id="choose_player" text="Choose a player" />
        <message id="maximum_player_creation_reached" text="Maximum player creation reached" />
        <message id="player_creation_failed" text="Player creation failed" />
        <!-- Base -->
        <message id="base_not_found" text="Base not found" />
        <message id="base_position_already_taken" text="The position is already taken" />
        <!-- Static buildings -->
        <message id="static_building_doesnt_exist" text="The requested building doesn't exist" />
        <!-- Buildings -->
        <message id="building_cannot_create" text="Cannot create the building" />
        <message id="building_not_found" text="Building not found" />
        <message id="building_already_exist" text="Building already exist" />
        <message id="building_max_level_reached" text="Max building level reached" />
        <!-- Buildings names -->
        <message id="building_mine_n" text="Mine" />
        <message id="building_storage_n" text="Storage" />
        <message id="building_shield_n" text="Shield" />
        <message id="building_pump_n" text="Pump" />
        <message id="building_power_factory_n" text="Power Factory" />
        <message id="building_embassy_n" text="Embassy" />
        <message id="building_operation_center_n" text="Operation Center" />
        <message id="building_robot_factory_n" text="Robot Factory" />
        <message id="building_market_n" text="Market" />
        <message id="building_module_factory_n" text="Module Factory" />
        <message id="building_structure_factory_n" text="Structure Factory" />
        <message id="building_spatial_elevator_n" text="Spatial Elevator" />
        <message id="building_silo_n" text="Silo" />
        <!-- Buildings descriptions -->
        <message id="building_mine_d" text="Metal is necessary to extract the main resources from the ground." />
        <message id="building_storage_d" text="The storage building increase your basement metal storage capacity. You can up this building to improve the capacity to your conveniences." />
        <message id="building_shield_d" text="The shield building increase your basement defense to protect yourself against ennemies attack." />
        <message id="building_pump_d" text="The pump is necessary to extract the main liquid resources." />
        <message id="building_power_factory_d" text="The power factory generate energy used by all buildings for a 100% efficiency." />
        <message id="building_embassy_d" text="Embassy manage your externals relations." />
        <message id="building_operation_center_d" text="The operation center manage all fleet trafic around your base" />
        <message id="building_robot_factory_d" text="description is not done, its in todo list" />
        <message id="building_market_d" text="description is not done, its in todo list" />
        <message id="building_module_factory_d" text="Module factory allow you to upgrade your ships and your building by putting modules engines on them" />
        <message id="building_structure_factory_d" text="Structure factory allow you to build the structure of your ships" />
        <message id="building_spatial_elevator_d" text="Description is not done, its in todo list" />
        <message id="building_silo_d" text="description is not done, its in todo list" />
        <!-- Items -->
        <message id="item_not_found" text="L'objet n'existe pas" />
        <message id="item_not_found_in_inventory" text="Item not found in inventory" />
        <message id="item_cannot_create" text="L'objet ne peut pas être créé" />
        <!-- Inventories -->
        <message id="inventory_not_found" text="L'inventaire n'existe pas" />
        <!-- Requirements -->
        <message id="you_dont_meet_building_requirement" text="You do not meet buildings requirements" />
        <message id="you_dont_meet_item_requirement" text="You do not meet items requirements" />
        <message id="you_dont_meet_resource_requirement" text="You do not meet resources requirements" />
        <!-- Items names -->
        <message id="resource_1_n" text="Metal" />
        <message id="resource_2_n" text="Carbon" />
        <message id="resource_3_n" text="Cristal" />
        <message id="resource_4_n" text="Methan" />
        <message id="resource_5_n" text="Water" />
        <message id="resource_steel_n" text="Acier" />
        <message id="resource_plastic_n" text="Plastic" />
        <message id="resource_tool_n" text="Tool" />
        <message id="resource_nanoliquid_n" text="Nanoliquide" />
        <message id="resource_septum_n" text="Septum" />
        <message id="structure_test_n" text="Structure Test" />
        <!-- Items descriptions -->
        <message id="resource_1_d" text="Oxyde de Fer description todo" />
        <message id="resource_2_d" text="Carbon description todo" />
        <message id="resource_3_d" text="Oxyde d'atemium description todo" />
        <message id="resource_4_d" text="Methane description todo" />
        <message id="resource_5_d" text="Water description todo" />
        <message id="resource_steel_d" text="Steel description todo" />
        <message id="resource_plastic_d" text="Plastic description todo" />
        <message id="resource_tool_d" text="Tool description todo" />
        <message id="resource_nanoliquid_d" text="Nanoliquid description todo" />
        <message id="resource_septum_d" text="Septum description todo" />
        <message id="structure_test_d" text="Structure créée pour effectuer des tests. A supprimer avant la release." />
    </messages>
</list>

=== BertrandD/mddl-server/dist/data/messages/fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/messages.xsd">
    <messages lang="FR">
        <message id="username_not_found" text="Nom d'utilisateur inconnu" />
        <message id="username_already_exist" text="Nom d'utilisateur déjà utilisé" />
        <message id="account_already_exist" text="Ce compte existe déjà" />
        <message id="incorrect_credentials" text="Mot de passe incorrect" />
        <message id="forbidden_name" text="Ce nom est interdit" />
        <message id="player_not_found" text="Ce joueur n'existe pas" />
        <message id="base_not_found" text="Cette base n'existe pas" />
    </messages>
</list>
