=== BertrandD/mddl-server/api/resources/data/xsd/shop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" type="categoryType" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="disabled" type="xs:boolean" use="optional" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="categoryType">
        <xs:sequence>
            <xs:element name="item" type="shopItemType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="shopItemType">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="count" type="xs:positiveInteger" use="required" />
        <xs:attribute name="price" type="xs:positiveInteger" use="required" />
        <xs:attribute name="disabled" type="xs:boolean" use="optional" />
    </xs:complexType>
</xs:schema>

=== BertrandD/mddl-server/resources/data/shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/shop.xsd">
    <category name="BOOST">
        <item id="boost_resource_feo_10_1week" count="1" price="100" /> <!-- Selected base boost FeO production by 10% during 1 week -->
        <item id="boost_resource_feo_20_1week" count="1" price="170" /> <!-- Selected base boost FeO production by 20% during 1 week -->
        <item id="boost_resource_feo_30_1week" count="1" price="250" /> <!-- Selected base boost FeO production by 30% during 1 week -->
        <item id="boost_resource_c_10_1week" count="1" price="100" /> <!-- Selected base boost C production by 10% during 1 week -->
        <item id="boost_resource_c_20_1week" count="1" price="170" /> <!-- Selected base boost C production by 20% during 1 week -->
        <item id="boost_resource_c_30_1week" count="1" price="250" /> <!-- Selected base boost C production by 30% during 1 week -->
        <item id="boost_resource_ato3_10_1week" count="1" price="100" /> <!-- Selected base boost AtO3 production by 10% during 1 week -->
        <item id="boost_resource_ato3_20_1week" count="1" price="170" /> <!-- Selected base boost AtO3 production by 20% during 1 week -->
        <item id="boost_resource_ato3_30_1week" count="1" price="250" /> <!-- Selected base boost AtO3 production by 30% during 1 week -->
        <item id="boost_resource_ch4_10_1week" count="1" price="100" /> <!-- Selected base boost CH4 production by 10% during 1 week -->
        <item id="boost_resource_ch4_20_1week" count="1" price="170" /> <!-- Selected base boost CH4 production by 20% during 1 week -->
        <item id="boost_resource_ch4_30_1week" count="1" price="250" /> <!-- Selected base boost CH4 production by 30% during 1 week -->
        <item id="boost_resource_h2o_10_1week" count="1" price="100" /> <!-- Selected base boost H2O production by 10% during 1 week -->
        <item id="boost_resource_h2o_20_1week" count="1" price="170" /> <!-- Selected base boost H2O production by 20% during 1 week -->
        <item id="boost_resource_h2o_30_1week" count="1" price="250" /> <!-- Selected base boost H2O production by 30% during 1 week -->
    </category>
    <category name="SKIN">
        <item id="skin_base_001" count="1" price="500" />
        <item id="skin_base_002" count="1" price="500" />
        <item id="skin_base_003" count="1" price="500" />
    </category>
    <category name="SERVICE">
        <item id="ticket_rename_player" count="1" price="350" />
        <item id="ticket_rename_base" count="1" price="25" />
        <item id="ticket_rename_moon" count="1" price="100" />
        <item id="ticket_rename_planet" count="1" price="125" />
    </category>
</list>

=== BertrandD/mddl-server/middlewar-boot/src/main/resources/data/shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/shop.xsd">
    <category name="BOOST">
        <item id="boost_resource_1_10_1week" count="1" price="100" /> <!-- Selected base boost metal production by 10% during 1 week -->
        <item id="boost_resource_1_20_1week" count="1" price="170" /> <!-- Selected base boost metal production by 20% during 1 week -->
        <item id="boost_resource_1_30_1week" count="1" price="250" /> <!-- Selected base boost metal production by 30% during 1 week -->
        <item id="boost_resource_2_10_1week" count="1" price="100" /> <!-- Selected base boost Carbon production by 10% during 1 week -->
        <item id="boost_resource_2_20_1week" count="1" price="170" /> <!-- Selected base boost Carbon production by 20% during 1 week -->
        <item id="boost_resource_2_30_1week" count="1" price="250" /> <!-- Selected base boost Carbon production by 30% during 1 week -->
        <item id="boost_resource_3_10_1week" count="1" price="100" /> <!-- Selected base boost Cristal production by 10% during 1 week -->
        <item id="boost_resource_3_20_1week" count="1" price="170" /> <!-- Selected base boost Cristal production by 20% during 1 week -->
        <item id="boost_resource_3_30_1week" count="1" price="250" /> <!-- Selected base boost Cristal production by 30% during 1 week -->
        <item id="boost_resource_4_10_1week" count="1" price="100" /> <!-- Selected base boost Methan production by 10% during 1 week -->
        <item id="boost_resource_4_20_1week" count="1" price="170" /> <!-- Selected base boost Methan production by 20% during 1 week -->
        <item id="boost_resource_4_30_1week" count="1" price="250" /> <!-- Selected base boost Methan production by 30% during 1 week -->
        <item id="boost_resource_5_10_1week" count="1" price="100" /> <!-- Selected base boost Water production by 10% during 1 week -->
        <item id="boost_resource_5_20_1week" count="1" price="170" /> <!-- Selected base boost Water production by 20% during 1 week -->
        <item id="boost_resource_5_30_1week" count="1" price="250" /> <!-- Selected base boost Water production by 30% during 1 week -->
    </category>
    <category name="SKIN">
        <item id="skin_base_001" count="1" price="500" />
        <item id="skin_base_002" count="1" price="500" />
        <item id="skin_base_003" count="1" price="500" />
    </category>
    <category name="SERVICE">
        <item id="ticket_rename_player" count="1" price="350" />
        <item id="ticket_rename_base" count="1" price="25" />
        <item id="ticket_rename_moon" count="1" price="100" />
        <item id="ticket_rename_planet" count="1" price="125" />
    </category>
</list>
